In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("C:\\Users\\supriya\\Downloads\\linear regression model for house price predicition\\business.csv")

In [4]:
df

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price
0,11-02-2022,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612"
1,11-02-2022,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612"
2,11-02-2022,Air India,AI,531,20:00,Delhi,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220"
3,11-02-2022,Air India,AI,839,21:25,Delhi,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450"
4,11-02-2022,Air India,AI,544,17:15,Delhi,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690"
...,...,...,...,...,...,...,...,...,...,...,...
93482,31-03-2022,Vistara,UK,822,09:45,Chennai,10h 05m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"69,265"
93483,31-03-2022,Vistara,UK,826,12:30,Chennai,10h 25m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,22:55,Hyderabad,"77,105"
93484,31-03-2022,Vistara,UK,832,07:05,Chennai,13h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"79,099"
93485,31-03-2022,Vistara,UK,828,07:00,Chennai,10h 00m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,17:00,Hyderabad,"81,585"
93486,31-03-2022,Vistara,UK,822,09:45,Chennai,10h 05m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"81,585"

In [5]:
df.shape

(93487, 11)

In [6]:
#get basics info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        93487 non-null  object
 1   airline     93487 non-null  object
 2   ch_code     93487 non-null  object
 3   num_code    93487 non-null  int64
 4   dep_time    93487 non-null  object
 5   from        93487 non-null  object
 6   time_taken  93487 non-null  object
 7   stop        93487 non-null  object
 8   arr_time    93487 non-null  object
 9   to          93487 non-null  object
 10  price       93487 non-null  object
dtypes: int64(1), object(10)
memory usage: 7.8+ MB

In [22]:
df["date"] = pd.to_datetime(df["date"], dayfirst=True)  # Set dayfirst=True for DD/MM/YYYY
df["day"] = df["date"].dt.day
df["month"] = df["date"].dt.month
df["year"] = df["date"].dt.year

In [23]:
df

,date,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,day,month,year
0,2022-02-11,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612",11,2,2022
1,2022-02-11,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612",11,2,2022
2,2022-02-11,Air India,AI,531,20:00,Delhi,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220",11,2,2022
3,2022-02-11,Air India,AI,839,21:25,Delhi,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450",11,2,2022
4,2022-02-11,Air India,AI,544,17:15,Delhi,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690",11,2,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93482,2022-03-31,Vistara,UK,822,09:45,Chennai,10h 05m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"69,265",31,3,2022
93483,2022-03-31,Vistara,UK,826,12:30,Chennai,10h 25m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,22:55,Hyderabad,"77,105",31,3,2022
93484,2022-03-31,Vistara,UK,832,07:05,Chennai,13h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"79,099",31,3,2022
93485,2022-03-31,Vistara,UK,828,07:00,Chennai,10h 00m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,17:00,Hyderabad,"81,585",31,3,2022
93486,2022-03-31,Vistara,UK,822,09:45,Chennai,10h 05m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"81,585",31,3,2022

In [24]:
df.drop("date",axis=1,inplace=True)

In [25]:
df

,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,day,month,year
0,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612",11,2,2022
1,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612",11,2,2022
2,Air India,AI,531,20:00,Delhi,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220",11,2,2022
3,Air India,AI,839,21:25,Delhi,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450",11,2,2022
4,Air India,AI,544,17:15,Delhi,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690",11,2,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...
93482,Vistara,UK,822,09:45,Chennai,10h 05m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"69,265",31,3,2022
93483,Vistara,UK,826,12:30,Chennai,10h 25m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,22:55,Hyderabad,"77,105",31,3,2022
93484,Vistara,UK,832,07:05,Chennai,13h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"79,099",31,3,2022
93485,Vistara,UK,828,07:00,Chennai,10h 00m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,17:00,Hyderabad,"81,585",31,3,2022
93486,Vistara,UK,822,09:45,Chennai,10h 05m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"81,585",31,3,2022

In [40]:
print(type(df["time_taken"].iloc[0]))

<class 'str'>

In [47]:

df["hours"] = df["time_taken"].str.split(" ").str[0]
df["minutes"] = df["time_taken"].str.split(" ").str[1]

In [48]:
df

,airline,ch_code,num_code,dep_time,from,time_taken,stop,arr_time,to,price,day,month,year,hours,minutes
0,Air India,AI,868,18:00,Delhi,02h 00m,non-stop,20:00,Mumbai,"25,612",11,2,2022,02h,00m
1,Air India,AI,624,19:00,Delhi,02h 15m,non-stop,21:15,Mumbai,"25,612",11,2,2022,02h,15m
2,Air India,AI,531,20:00,Delhi,24h 45m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220",11,2,2022,24h,45m
3,Air India,AI,839,21:25,Delhi,26h 30m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450",11,2,2022,26h,30m
4,Air India,AI,544,17:15,Delhi,06h 40m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690",11,2,2022,06h,40m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93482,Vistara,UK,822,09:45,Chennai,10h 05m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"69,265",31,3,2022,10h,05m
93483,Vistara,UK,826,12:30,Chennai,10h 25m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,22:55,Hyderabad,"77,105",31,3,2022,10h,25m
93484,Vistara,UK,832,07:05,Chennai,13h 50m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"79,099",31,3,2022,13h,50m
93485,Vistara,UK,828,07:00,Chennai,10h 00m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,17:00,Hyderabad,"81,585",31,3,2022,10h,00m
93486,Vistara,UK,822,09:45,Chennai,10h 05m,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"81,585",31,3,2022,10h,05m

In [50]:
df.drop("time_taken", axis=1,inplace=True)

In [51]:
df

,airline,ch_code,num_code,dep_time,from,stop,arr_time,to,price,day,month,year,hours,minutes
0,Air India,AI,868,18:00,Delhi,non-stop,20:00,Mumbai,"25,612",11,2,2022,02h,00m
1,Air India,AI,624,19:00,Delhi,non-stop,21:15,Mumbai,"25,612",11,2,2022,02h,15m
2,Air India,AI,531,20:00,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220",11,2,2022,24h,45m
3,Air India,AI,839,21:25,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450",11,2,2022,26h,30m
4,Air India,AI,544,17:15,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690",11,2,2022,06h,40m
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93482,Vistara,UK,822,09:45,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"69,265",31,3,2022,10h,05m
93483,Vistara,UK,826,12:30,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,22:55,Hyderabad,"77,105",31,3,2022,10h,25m
93484,Vistara,UK,832,07:05,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"79,099",31,3,2022,13h,50m
93485,Vistara,UK,828,07:00,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,17:00,Hyderabad,"81,585",31,3,2022,10h,00m
93486,Vistara,UK,822,09:45,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"81,585",31,3,2022,10h,05m

In [52]:
df.head()

,airline,ch_code,num_code,dep_time,from,stop,arr_time,to,price,day,month,year,hours,minutes
0,Air India,AI,868,18:00,Delhi,non-stop,20:00,Mumbai,"25,612",11,2,2022,02h,00m
1,Air India,AI,624,19:00,Delhi,non-stop,21:15,Mumbai,"25,612",11,2,2022,02h,15m
2,Air India,AI,531,20:00,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220",11,2,2022,24h,45m
3,Air India,AI,839,21:25,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450",11,2,2022,26h,30m
4,Air India,AI,544,17:15,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690",11,2,2022,06h,40m

In [61]:
df["arr_hours"] = df["arr_time"].str.split(":").str[0]
df["arr_minutes"] = df["arr_time"].str.split(" ").str[1]

In [62]:
df

,airline,ch_code,num_code,dep_time,from,stop,arr_time,to,price,day,month,year,hours,minutes,arr_hours,arr_minutes
0,Air India,AI,868,18:00,Delhi,non-stop,20:00,Mumbai,"25,612",11,2,2022,02h,00m,20,NaN
1,Air India,AI,624,19:00,Delhi,non-stop,21:15,Mumbai,"25,612",11,2,2022,02h,15m,21,NaN
2,Air India,AI,531,20:00,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220",11,2,2022,24h,45m,20,NaN
3,Air India,AI,839,21:25,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450",11,2,2022,26h,30m,23,NaN
4,Air India,AI,544,17:15,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690",11,2,2022,06h,40m,23,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93482,Vistara,UK,822,09:45,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"69,265",31,3,2022,10h,05m,19,NaN
93483,Vistara,UK,826,12:30,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,22:55,Hyderabad,"77,105",31,3,2022,10h,25m,22,NaN
93484,Vistara,UK,832,07:05,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"79,099",31,3,2022,13h,50m,20,NaN
93485,Vistara,UK,828,07:00,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,17:00,Hyderabad,"81,585",31,3,2022,10h,00m,17,NaN
93486,Vistara,UK,822,09:45,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"81,585",31,3,2022,10h,05m,19,NaN

In [66]:
df["arr_time"] = df["arr_time"].astype(str)
df["arr_minutes"] = df["arr_time"].str.split(":").str[1]

In [77]:
df

,airline,ch_code,num_code,from,stop,arr_time,to,price,day,month,year,hours,minutes,arr_hours,arr_minutes,dep_hour,dep_minutes
0,Air India,AI,868,Delhi,non-stop,20:00,Mumbai,"25,612",11,2,2022,02h,00m,20,00,18,00
1,Air India,AI,624,Delhi,non-stop,21:15,Mumbai,"25,612",11,2,2022,02h,15m,21,15,19,00
2,Air India,AI,531,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220",11,2,2022,24h,45m,20,45,20,00
3,Air India,AI,839,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450",11,2,2022,26h,30m,23,55,21,25
4,Air India,AI,544,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690",11,2,2022,06h,40m,23,55,17,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93482,Vistara,UK,822,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"69,265",31,3,2022,10h,05m,19,50,09,45
93483,Vistara,UK,826,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,22:55,Hyderabad,"77,105",31,3,2022,10h,25m,22,55,12,30
93484,Vistara,UK,832,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"79,099",31,3,2022,13h,50m,20,55,07,05
93485,Vistara,UK,828,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,17:00,Hyderabad,"81,585",31,3,2022,10h,00m,17,00,07,00
93486,Vistara,UK,822,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"81,585",31,3,2022,10h,05m,19,50,09,45

In [72]:

df["dep_hour"] = df["dep_time"].str.split(":").str[0]
df["dep_minutes"] = df["dep_time"].str.split(":").str[1]

In [73]:
df

,airline,ch_code,num_code,dep_time,from,stop,arr_time,to,price,day,month,year,hours,minutes,arr_hours,arr_minutes,dep_hour,dep_minutes
0,Air India,AI,868,18:00,Delhi,non-stop,20:00,Mumbai,"25,612",11,2,2022,02h,00m,20,00,18,00
1,Air India,AI,624,19:00,Delhi,non-stop,21:15,Mumbai,"25,612",11,2,2022,02h,15m,21,15,19,00
2,Air India,AI,531,20:00,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220",11,2,2022,24h,45m,20,45,20,00
3,Air India,AI,839,21:25,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450",11,2,2022,26h,30m,23,55,21,25
4,Air India,AI,544,17:15,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690",11,2,2022,06h,40m,23,55,17,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93482,Vistara,UK,822,09:45,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"69,265",31,3,2022,10h,05m,19,50,09,45
93483,Vistara,UK,826,12:30,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,22:55,Hyderabad,"77,105",31,3,2022,10h,25m,22,55,12,30
93484,Vistara,UK,832,07:05,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"79,099",31,3,2022,13h,50m,20,55,07,05
93485,Vistara,UK,828,07:00,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,17:00,Hyderabad,"81,585",31,3,2022,10h,00m,17,00,07,00
93486,Vistara,UK,822,09:45,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"81,585",31,3,2022,10h,05m,19,50,09,45

In [74]:
df.drop("dep_time",axis=1,inplace=True)

In [76]:
df

,airline,ch_code,num_code,from,stop,arr_time,to,price,day,month,year,hours,minutes,arr_hours,arr_minutes,dep_hour,dep_minutes
0,Air India,AI,868,Delhi,non-stop,20:00,Mumbai,"25,612",11,2,2022,02h,00m,20,00,18,00
1,Air India,AI,624,Delhi,non-stop,21:15,Mumbai,"25,612",11,2,2022,02h,15m,21,15,19,00
2,Air India,AI,531,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:45,Mumbai,"42,220",11,2,2022,24h,45m,20,45,20,00
3,Air India,AI,839,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"44,450",11,2,2022,26h,30m,23,55,21,25
4,Air India,AI,544,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,23:55,Mumbai,"46,690",11,2,2022,06h,40m,23,55,17,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93482,Vistara,UK,822,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"69,265",31,3,2022,10h,05m,19,50,09,45
93483,Vistara,UK,826,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,22:55,Hyderabad,"77,105",31,3,2022,10h,25m,22,55,12,30
93484,Vistara,UK,832,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,20:55,Hyderabad,"79,099",31,3,2022,13h,50m,20,55,07,05
93485,Vistara,UK,828,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,17:00,Hyderabad,"81,585",31,3,2022,10h,00m,17,00,07,00
93486,Vistara,UK,822,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,19:50,Hyderabad,"81,585",31,3,2022,10h,05m,19,50,09,45

In [79]:
df.drop("arr_time", axis=1, inplace=True)

In [80]:
df

,airline,ch_code,num_code,from,stop,to,price,day,month,year,hours,minutes,arr_hours,arr_minutes,dep_hour,dep_minutes
0,Air India,AI,868,Delhi,non-stop,Mumbai,"25,612",11,2,2022,02h,00m,20,00,18,00
1,Air India,AI,624,Delhi,non-stop,Mumbai,"25,612",11,2,2022,02h,15m,21,15,19,00
2,Air India,AI,531,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,Mumbai,"42,220",11,2,2022,24h,45m,20,45,20,00
3,Air India,AI,839,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,Mumbai,"44,450",11,2,2022,26h,30m,23,55,21,25
4,Air India,AI,544,Delhi,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,Mumbai,"46,690",11,2,2022,06h,40m,23,55,17,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93482,Vistara,UK,822,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,Hyderabad,"69,265",31,3,2022,10h,05m,19,50,09,45
93483,Vistara,UK,826,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,Hyderabad,"77,105",31,3,2022,10h,25m,22,55,12,30
93484,Vistara,UK,832,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,Hyderabad,"79,099",31,3,2022,13h,50m,20,55,07,05
93485,Vistara,UK,828,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,Hyderabad,"81,585",31,3,2022,10h,00m,17,00,07,00
93486,Vistara,UK,822,Chennai,1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t...,Hyderabad,"81,585",31,3,2022,10h,05m,19,50,09,45

In [82]:
df["stop"].unique()

array(['non-stop ',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IDR\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXU\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Chennai\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Lucknow\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia STV\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Hyderabad\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia GAY\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '2+-stop',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Guwahati\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia GAU\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia VTZ\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia NDC\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia IXE\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Raipur\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia PAT\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia RPR\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Patna\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Kolkata\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia HYD\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Delhi\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Bhubaneswar\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia BBI\n\t\t\t\t\t\t\t\t\t\t\t\t',
       '1-stop\n\t\t\t\t\t\t\t\t\t\t\t\tVia Surat\n\t\t\t\t\t\t\t\t\t\t\t\t'],
      dtype=object)

In [89]:
df[df["stop"].isnull()]

Empty DataFrame
Columns: [airline, ch_code, num_code, from, stop, to, price, day, month, year, hours, minutes, arr_hours, arr_minutes, dep_hour, dep_minutes]
Index: []

In [90]:
df["stop"]=df["stop"].str.replace(r'\s+','',regex=True).str.strip()

In [91]:
df

,airline,ch_code,num_code,from,stop,to,price,day,month,year,hours,minutes,arr_hours,arr_minutes,dep_hour,dep_minutes
0,Air India,AI,868,Delhi,non-stop,Mumbai,"25,612",11,2,2022,02h,00m,20,00,18,00
1,Air India,AI,624,Delhi,non-stop,Mumbai,"25,612",11,2,2022,02h,15m,21,15,19,00
2,Air India,AI,531,Delhi,1-stop,Mumbai,"42,220",11,2,2022,24h,45m,20,45,20,00
3,Air India,AI,839,Delhi,1-stop,Mumbai,"44,450",11,2,2022,26h,30m,23,55,21,25
4,Air India,AI,544,Delhi,1-stop,Mumbai,"46,690",11,2,2022,06h,40m,23,55,17,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93482,Vistara,UK,822,Chennai,1-stop,Hyderabad,"69,265",31,3,2022,10h,05m,19,50,09,45
93483,Vistara,UK,826,Chennai,1-stop,Hyderabad,"77,105",31,3,2022,10h,25m,22,55,12,30
93484,Vistara,UK,832,Chennai,1-stop,Hyderabad,"79,099",31,3,2022,13h,50m,20,55,07,05
93485,Vistara,UK,828,Chennai,1-stop,Hyderabad,"81,585",31,3,2022,10h,00m,17,00,07,00
93486,Vistara,UK,822,Chennai,1-stop,Hyderabad,"81,585",31,3,2022,10h,05m,19,50,09,45

In [96]:
df.rename(columns={"from":"source"},inplace=True)
df.rename(columns={"to":"destination"},inplace=True)

In [97]:
df

,airline,ch_code,num_code,source,stop,destination,price,day,month,year,hours,minutes,arr_hours,arr_minutes,dep_hour,dep_minutes
0,Air India,AI,868,Delhi,non-stop,Mumbai,"25,612",11,2,2022,02h,00m,20,00,18,00
1,Air India,AI,624,Delhi,non-stop,Mumbai,"25,612",11,2,2022,02h,15m,21,15,19,00
2,Air India,AI,531,Delhi,1-stop,Mumbai,"42,220",11,2,2022,24h,45m,20,45,20,00
3,Air India,AI,839,Delhi,1-stop,Mumbai,"44,450",11,2,2022,26h,30m,23,55,21,25
4,Air India,AI,544,Delhi,1-stop,Mumbai,"46,690",11,2,2022,06h,40m,23,55,17,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93482,Vistara,UK,822,Chennai,1-stop,Hyderabad,"69,265",31,3,2022,10h,05m,19,50,09,45
93483,Vistara,UK,826,Chennai,1-stop,Hyderabad,"77,105",31,3,2022,10h,25m,22,55,12,30
93484,Vistara,UK,832,Chennai,1-stop,Hyderabad,"79,099",31,3,2022,13h,50m,20,55,07,05
93485,Vistara,UK,828,Chennai,1-stop,Hyderabad,"81,585",31,3,2022,10h,00m,17,00,07,00
93486,Vistara,UK,822,Chennai,1-stop,Hyderabad,"81,585",31,3,2022,10h,05m,19,50,09,45

,airline,ch_code,num_code,source,stop,destination,price,day,month,year,hours,minutes,arr_hours,arr_minutes,dep_hour,dep_minutes
0,Air India,AI,868,Delhi,non-stop,Mumbai,"25,612",11,2,2022,02h,00m,20,00,18,00
1,Air India,AI,624,Delhi,non-stop,Mumbai,"25,612",11,2,2022,02h,15m,21,15,19,00
2,Air India,AI,531,Delhi,1-stop,Mumbai,"42,220",11,2,2022,24h,45m,20,45,20,00
3,Air India,AI,839,Delhi,1-stop,Mumbai,"44,450",11,2,2022,26h,30m,23,55,21,25
4,Air India,AI,544,Delhi,1-stop,Mumbai,"46,690",11,2,2022,06h,40m,23,55,17,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93482,Vistara,UK,822,Chennai,1-stop,Hyderabad,"69,265",31,3,2022,10h,05m,19,50,09,45
93483,Vistara,UK,826,Chennai,1-stop,Hyderabad,"77,105",31,3,2022,10h,25m,22,55,12,30
93484,Vistara,UK,832,Chennai,1-stop,Hyderabad,"79,099",31,3,2022,13h,50m,20,55,07,05
93485,Vistara,UK,828,Chennai,1-stop,Hyderabad,"81,585",31,3,2022,10h,00m,17,00,07,00
93486,Vistara,UK,822,Chennai,1-stop,Hyderabad,"81,585",31,3,2022,10h,05m,19,50,09,45

In [106]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93487 entries, 0 to 93486
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   airline      93487 non-null  object
 1   ch_code      93487 non-null  object
 2   num_code     93487 non-null  int64
 3   source       93487 non-null  object
 4   stop         93487 non-null  object
 5   destination  93487 non-null  object
 6   price        93487 non-null  object
 7   day          93487 non-null  int32
 8   month        93487 non-null  int32
 9   year         93487 non-null  int32
 10  hours        93487 non-null  object
 11  minutes      93487 non-null  object
 12  arr_hours    93487 non-null  object
 13  arr_minutes  93487 non-null  object
 14  dep_hour     93487 non-null  object
 15  dep_minutes  93487 non-null  object
dtypes: int32(3), int64(1), object(12)
memory usage: 10.3+ MB

In [108]:
df.to_csv("flights_data_csv",index=False)

,airline,ch_code,num_code,source,stop,destination,price,day,month,year,hours,minutes,arr_hours,arr_minutes,dep_hour,dep_minutes
0,Air India,AI,868,Delhi,non-stop,Mumbai,"25,612",11,2,2022,02h,00m,20,00,18,00
1,Air India,AI,624,Delhi,non-stop,Mumbai,"25,612",11,2,2022,02h,15m,21,15,19,00
2,Air India,AI,531,Delhi,1-stop,Mumbai,"42,220",11,2,2022,24h,45m,20,45,20,00
3,Air India,AI,839,Delhi,1-stop,Mumbai,"44,450",11,2,2022,26h,30m,23,55,21,25
4,Air India,AI,544,Delhi,1-stop,Mumbai,"46,690",11,2,2022,06h,40m,23,55,17,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93482,Vistara,UK,822,Chennai,1-stop,Hyderabad,"69,265",31,3,2022,10h,05m,19,50,09,45
93483,Vistara,UK,826,Chennai,1-stop,Hyderabad,"77,105",31,3,2022,10h,25m,22,55,12,30
93484,Vistara,UK,832,Chennai,1-stop,Hyderabad,"79,099",31,3,2022,13h,50m,20,55,07,05
93485,Vistara,UK,828,Chennai,1-stop,Hyderabad,"81,585",31,3,2022,10h,00m,17,00,07,00
93486,Vistara,UK,822,Chennai,1-stop,Hyderabad,"81,585",31,3,2022,10h,05m,19,50,09,45